### ISSUE TITLE
Preact Module parse failed

### ISSUE THREAD

**Issue by ywzhaiqi** [jokester/typescript-boilerplate#3]
git clone webpack-preact 分支后，运行 npm run webpack

    Module parse failed:
    You may need an appropriate loader to handle this file type.
    |         console.log("accept handler", [].slice.call(arguments));
    |         l("m=", m);
    |         preact.render(<Greeting val={m.v}/>, document.body);
    |     });
    | }

**Comment by jokester** [comment]
不好意思，我晚上看一下 (最近试图把webpack/HMR和preact一起用，可能是设置问题)

**Comment by jokester** [comment]
@ywzhaiqi webpack-preact 分支应该已经改好了, 你有时间可以再试一下, 没问题关掉issue就可. 谢谢!
